/** @type {import('tailwindcss').Config}*/
const config = {
  content: ["./src/**/*.{html,js,svelte,ts}"],

  theme: {
    extend: {
      colors: {
        "unitto": {
          "light": {
            "primary": "#196c32",
            "onPrimary": "#ffffff",
            "primaryContainer": "#a3f6ab",
            "onPrimaryContainer": "#002109",
            "primaryFixed": "#a3f6ab",
            "onPrimaryFixed": "#002109",
            "primaryFixedDim": "#87d991",
            "onPrimaryFixedVariant": "#005320",
            "secondary": "#516351",
            "onSecondary": "#ffffff",
            "secondaryContainer": "#d4e8d1",
            "onSecondaryContainer": "#0f1f11",
            "secondaryFixed": "#d4e8d1",
            "onSecondaryFixed": "#0f1f11",
            "secondaryFixedDim": "#b8ccb6",
            "onSecondaryFixedVariant": "#3a4b3a",
            "tertiary": "#39656c",
            "onTertiary": "#ffffff",
            "tertiaryContainer": "#bdeaf3",
            "onTertiaryContainer": "#001f24",
            "tertiaryFixed": "#bdeaf3",
            "onTertiaryFixed": "#001f24",
            "tertiaryFixedDim": "#a1ced7",
            "onTertiaryFixedVariant": "#1f4d54",
            "error": "#ba1a1a",
            "errorContainer": "#ffdad6",
            "onError": "#ffffff",
            "onErrorContainer": "#410002",
            "background": "#fcfdf7",
            "onBackground": "#1a1c19",
            "outline": "#727970",
            "inverseOnSurface": "#f0f1eb",
            "inverseSurface": "#2e312d",
            "inversePrimary": "#87d991",
            "shadow": "#000000",
            "surfaceTint": "#196c32",
            "outlineVariant": "#c1c9be",
            "scrim": "#000000",
            "surface": "#f9faf4",
            "onSurface": "#1a1c19",
            "surfaceVariant": "#dde5d9",
            "onSurfaceVariant": "#424940",
            "surfaceContainerHighest": "#e2e3dd",
            "surfaceContainerHigh": "#e7e9e3",
            "surfaceContainer": "#edeee9",
            "surfaceContainerLow": "#f3f4ee",
            "surfaceContainerLowest": "#ffffff",
            "surfaceDim": "#d9dbd5",
            "surfaceBright": "#f9faf4",
            "surfaceContainer-active-hover": "#C4D8C4",
            "surfaceContainer-inactive-hover": "#EAECE6"
          },
          "dark": {
            "primary": "#87d991",
            "onPrimary": "#003914",
            "primaryContainer": "#005320",
            "onPrimaryContainer": "#a3f6ab",
            "primaryFixed": "#a3f6ab",
            "onPrimaryFixed": "#002109",
            "primaryFixedDim": "#87d991",
            "onPrimaryFixedVariant": "#005320",
            "secondary": "#b8ccb6",
            "onSecondary": "#243425",
            "secondaryContainer": "#3a4b3a",
            "onSecondaryContainer": "#d4e8d1",
            "secondaryFixed": "#d4e8d1",
            "onSecondaryFixed": "#0f1f11",
            "secondaryFixedDim": "#b8ccb6",
            "onSecondaryFixedVariant": "#3a4b3a",
            "tertiary": "#a1ced7",
            "onTertiary": "#00363d",
            "tertiaryContainer": "#1f4d54",
            "onTertiaryContainer": "#bdeaf3",
            "tertiaryFixed": "#bdeaf3",
            "onTertiaryFixed": "#001f24",
            "tertiaryFixedDim": "#a1ced7",
            "onTertiaryFixedVariant": "#1f4d54",
            "error": "#ffb4ab",
            "errorContainer": "#93000a",
            "onError": "#690005",
            "onErrorContainer": "#ffdad6",
            "background": "#1a1c19",
            "onBackground": "#e2e3dd",
            "outline": "#8b9389",
            "inverseOnSurface": "#1a1c19",
            "inverseSurface": "#e2e3dd",
            "inversePrimary": "#196c32",
            "shadow": "#000000",
            "surfaceTint": "#87d991",
            "outlineVariant": "#424940",
            "scrim": "#000000",
            "surface": "#111411",
            "onSurface": "#c6c7c2",
            "surfaceVariant": "#424940",
            "onSurfaceVariant": "#c1c9be",
            "surfaceContainerHighest": "#333532",
            "surfaceContainerHigh": "#282b27",
            "surfaceContainer": "#1e201d",
            "surfaceContainerLow": "#1a1c19",
            "surfaceContainerLowest": "#0c0f0c",
            "surfaceDim": "#111411",
            "surfaceBright": "#373a36",
            "surfaceContainer-active-hover": "#455A47",
            "surfaceContainer-inactive-hover": "#364036"
          },
        }
      }
    },
  },

  plugins: [],
};

module.exports = config;
