<script lang="ts">
  import WallOfText from "../../../components/WallOfText.svelte";
  import TextTitle from "../../../components/TextTitle.svelte";
  import TextBodyLink from "../../../components/TextBodyLink.svelte";
  import Footer from "../Footer.svelte";
  import TextHeader1 from "../../../components/TextHeader1.svelte";
  import { IndexxoTheme } from "../IndexxoTheme";
</script>

<WallOfText>
  <TextTitle>Privacy Policy</TextTitle>
  <p>
    This privacy policy applies to the Indexxo app (hereby referred to as
    "Application") that was created by Sad Ellie (hereby referred to as "Service
    Provider") as an Open Source service. This service is intended for use "AS
    IS".
  </p>

  <TextHeader1 theme={IndexxoTheme}>
    What information does the Application obtain and how is it used?
  </TextHeader1>

  <p>
    The Application processes file storage content that user selects. This
    information is used to generate and provide a statistical report. This data
    is stored locally and is never send anywhere by the Application. You have
    full control over how and what information is processed. You may instruct
    the Application to create, move or delete files.
  </p>

  <TextHeader1 theme={IndexxoTheme}>
    Does the Application collect precise real time location information of the
    device?
  </TextHeader1>

  <p>
    This Application does not collect precise information about the location of
    your device.
  </p>

  <TextHeader1 theme={IndexxoTheme}>
    Do third parties see and/or have access to information obtained by the
    Application?
  </TextHeader1>

  <p>No data is shared with third parties.</p>

  <TextHeader1 theme={IndexxoTheme}>What are my opt-out rights?</TextHeader1>

  <p>
    You can stop all collection of information by the Application easily by
    uninstalling it. You may use the standard uninstall processes as may be
    available as part of your device.
  </p>

  <TextHeader1 theme={IndexxoTheme}>Children</TextHeader1>

  <p>
    The Application is not used to knowingly solicit data from or market to
    children under the age of 13. The Service Provider does not knowingly
    collect personally identifiable information from children. The Service
    Provider encourages all children to never submit any personally identifiable
    information through the Application and/or Services. The Service Provider
    encourage parents and legal guardians to monitor their children's Internet
    usage and to help enforce this Policy by instructing their children never to
    provide personally identifiable information through the Application and/or
    Services without their permission. If you have reason to believe that a
    child has provided personally identifiable information to the Service
    Provider through the Application and/or Services, please contact the Service
    Provider (<TextBodyLink href="mailto://sadellie.dev@gmail.com"
      ><span class="font-bold hover:underline">sadellie.dev@gmail.com</span
      ></TextBodyLink
    >) so that I will be able to take the necessary actions. You must also be
    at least 16 years of age to consent to the processing of your personally
    identifiable information in your country (in some countries I may allow your
    parent or guardian to do so on your behalf).
  </p>

  <TextHeader1 theme={IndexxoTheme}>Security</TextHeader1>

  <p>
    The Application is not responsible for safeguarding the confidentiality of
    your information.
  </p>

  <TextHeader1 theme={IndexxoTheme}>Changes</TextHeader1>

  <p>
    This Privacy Policy may be updated from time to time for any reason. The
    Service Provider will notify you of any changes to their Privacy Policy by
    updating this page with the new Privacy Policy. You are advised to consult
    this Privacy Policy regularly for any changes, as continued use is deemed
    approval of all changes.
  </p>

  <p>This privacy policy is effective as of 2024-09-21</p>

  <TextHeader1 theme={IndexxoTheme}>Your Consent</TextHeader1>

  <p>
    By using the Application, you are consenting to the processing of your
    information as set forth in this Privacy Policy now and as amended by the
    Service Provider.
  </p>

  <TextHeader1 theme={IndexxoTheme}>Contact Me</TextHeader1>

  <p>
    If you have any questions regarding privacy while using the Application, or
    have questions about the practices, please contact the Service Provider via
    email at <TextBodyLink href="mailto://sadellie.dev@gmail.com"
    ><span class="font-bold hover:underline">sadellie.dev@gmail.com</span
    ></TextBodyLink
  >.
  </p>

  <p>
    This privacy policy page was generated by <TextBodyLink
      href="https://app-privacy-policy-generator.nisrulz.com/"
    >
      <span class="font-bold hover:underline">App Privacy Policy Generator</span
      >
    </TextBodyLink>
  </p>

  <Footer />
</WallOfText>
