<script lang="ts">
  import Footer from "../Footer.svelte";
  import TextHeader1 from "../../../components/TextHeader1.svelte";
  import TextTitle from "../../../components/TextTitle.svelte";
  import WallOfText from "../../../components/WallOfText.svelte";
  import { UnittoTheme } from "../UnittoTheme";
</script>

<WallOfText>
  <TextTitle>Terms &amp; Conditions</TextTitle>
  <p>
    By downloading or using the app, these terms will automatically apply to you
    – you should make sure therefore that you read them carefully before using
    the app. This software is licensed under GNU General Public License v3.0: <a
      class="font-medium text-blue-700 visited:text-fuchsia-700 hover:text-blue-900 hover:underline"
      href="https://github.com/sadellie/unitto/blob/master/LICENSE"
    >
      https://github.com/sadellie/unitto/blob/master/LICENSE
    </a>
  </p>
  <TextHeader1 theme={UnittoTheme}
    >Changes to This Terms and Conditions</TextHeader1
  >
  <p>
    I may update our Terms and Conditions from time to time. Thus, you are
    advised to review this page periodically for any changes. I will notify you
    of any changes by posting the new Terms and Conditions on this page.
  </p>
  <p>These terms and conditions are effective as of 2025-09-15</p>
  <TextHeader1 theme={UnittoTheme}>Contact Us</TextHeader1>
  <p>
    If you have any questions or suggestions about my Terms and Conditions, do
    not hesitate to contact me at <a
      class="font-medium text-blue-700 visited:text-fuchsia-700 hover:text-blue-900 hover:underline"
      href="mailto:sadellie.dev@gmail.com"
    >
      sadellie.dev@gmail.com
    </a>
  </p>
  <p>
    This Terms and Conditions page was generated by <a
      class="font-medium text-blue-700 visited:text-fuchsia-700 hover:text-blue-900 hover:underline"
      href="https://app-privacy-policy-generator.nisrulz.com/"
    >
      App Privacy Policy Generator
    </a>
  </p>
  <hr />
  <Footer />
</WallOfText>
